### ISSUE TITLE
Twitter @koebutaslayer を確保

### ISSUE THREAD

**Issue by otofune** [albno273/KoebutaSlayer#1]
https://twitter.com/albNo273/status/836967429272018944 の機能を使用するに当たり、現在は koebutaslayer が確保されていないので問題になりませんが今後確保された場合を考えて。

**Comment by albno273** [comment]
全く考慮しておりませんでした、申し訳ありません……。:bow:

@koebutaslayer につきましては[こちらでIDを確保](https://twitter.com/koebutaslayer)することで対処いたしました。
![@koebutaslayer](https://cloud.githubusercontent.com/assets/19812219/23576558/2213b364-00ec-11e7-9ecd-8111c8144fa4.png)

ありがとうございました！
